version: '3.8'

services:
  incident-service:
    build: .
    container_name: incident-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://incident-service-database.cq3o0gaucli6.us-east-1.rds.amazonaws.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Incident1234#
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    networks:
      - incident-net

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: incidentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - incident-net

volumes:
  postgres-data:

networks:
  incident-net:
